### ISSUE TITLE
Support for 'md5sum'  instead of md5 for linux command line

### ISSUE THREAD

**Issue by z-w123** [nadimm-rahman/ena-analysis-submitter#5]
https://github.com/nadimm-rahman/ena-analysis-submitter/blob/5a1438c71c90302309a7ee2c33c875cfba76ea76/bin/analysis_submission.py#L157

The md5 command does not work in linux based command lines (e.g. git bash or ubuntu) and thus prevents the script from running. It would be great to include a generic md5 calculator (if one exists) or for the script to support other checksum commands, such as md5sum.

**Comment by davidyuyuan** [comment]
+1

**Comment by nadimm-rahman** [comment]
This has been addressed in release 2.0.0. Thanks for raising this!
